name: YIKES, Inc. CI Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
          git fetch --prune --unshallow

    - name: GitHub Action for WP Engine Git Deployment
      uses: yikesinc/github-action-wpengine-git-deploy@master
      env:
        WPENGINE_SITE_NAME: 'yikescloud'
        LOCAL_BRANCH: 'master'
        WP_ENGINE_ENV: 'production'
        WPENGINE_SSH_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        WPENGINE_SSH_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}